language: cpp
sudo: required
dist: trusty 
addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    packages:
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - g++-5 # need at least gcc 5 because clang uses gcc stl
            - clang-3.8
            - boost1.74
      env: COMPILER=clang++-3.8
      
before_install:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        sudo apt-get install libboost-all-dev;
      fi
      
script: mkdir build && cd build && cmake -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=Release -DDISRUPTOR_BUILD_TESTS=true .. && make VERBOSE=1 && make test
branches:
  only:
    - master
